load("//eden/scm:targets.bzl", "rust_python_library")

oncall("sapling")

rust_python_library(
    name = "pygerrit",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:serde_json",
        "//eden/scm/lib/config/model:configmodel",
        "//eden/scm/lib/cpython-ext:cpython-ext",
        "//eden/scm/lib/gerrit:gerrit",
    ],
)
