load("@fbcode_macros//build_defs:rust_library.bzl", "rust_library")

oncall("sapling")

rust_library(
    name = "gerrit",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:url",
        "//eden/scm/lib/config/model:configmodel",
        "//eden/scm/lib/http-client:http-client",
    ],
)
