name: Release - Homebrew macOS-arm64
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release, e.g. 1.2.3'
        required: true
  push:
    tags:
      - v*
      - test-release-*

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v6
    - name: Set version
      run: |
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        VERSION="${VERSION#v}"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "TAG=v${VERSION}" >> $GITHUB_ENV
    - name: Build bottle
      run: eden/scm/packaging/mac/build_bottle.sh "$VERSION"
