name: Release - Homebrew macOS-arm64
on:
  workflow_dispatch: null
  push:
    tags:
    - v*
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
    - name: Grant Access
      run: git config --global --add safe.directory "$PWD"
    - name: set-env SAPLING_VERSION
      shell: bash
      run: echo "SAPLING_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
    - name: Create local tap
      run: |
        brew tap-new lucasingels/sapling
        eden/scm/packaging/mac/prepare_formula.py \
          -t aarch64-apple-darwin \
          -r $SAPLING_VERSION \
          -o $(brew --repository lucasingels/sapling)/Formula/sapling.rb
        cd $(brew --repository lucasingels/sapling)
        git add Formula/sapling.rb
        git commit -m "Add sapling formula"
    - name: Install and build Sapling bottle
      run: HOMEBREW_NO_INSTALL_FROM_API=1 HOMEBREW_FAIL_LOG_LINES=100 brew install --build-bottle lucasingels/sapling/sapling
    - name: Create Sapling bottle
      run: HOMEBREW_NO_INSTALL_FROM_API=1 brew bottle lucasingels/sapling/sapling
    - name: Rename bottle
      run: mv sapling*.bottle.tar.gz sapling-${{ env.SAPLING_VERSION }}.arm64.bottle.tar.gz
    - name: Create pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh bash ci/create-release.sh ${{ env.SAPLING_VERSION }}
    - name: Upload Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: bash ci/retry.sh gh release upload --clobber ${{ env.SAPLING_VERSION }} sapling-${{ env.SAPLING_VERSION }}.arm64.bottle.tar.gz
